name: Robô Mestre dos Greens (Alavancagem)

on:
  schedule:
    # Horários em UTC (Brasil é UTC-3)
    # 09:00 UTC = 06:00 Brasil
    # 12:00 UTC = 09:00 Brasil
    # 15:00 UTC = 12:00 Brasil
    # 18:00 UTC = 15:00 Brasil
    # 21:00 UTC = 18:00 Brasil
    - cron: '0 9,12,15,18,21 * * *'

  workflow_dispatch: # Permite rodar manualmente (botão Run workflow)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas
        run: |
          pip install pandas requests scipy plotly

      - name: Rodar o Robô
        env: 
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python app.py
